spring:
  application:
    name: actividadDos
  datasource:
    url: jdbc:postgresql://db:5432/estudiantes_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

data:
  dir: /mnt/persistencia
  file: students.dat

app:
  id: Programa 2

service:
  id: ${HOSTNAME:Servidor 1}